// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZaxeiyyocfo2pzIVH_Y0kh9HbB50hAyk',
    appId: '1:348036739477:web:d01a159b999a6a8065c69c',
    messagingSenderId: '348036739477',
    projectId: 'prowork-a9a06',
    authDomain: 'prowork-a9a06.firebaseapp.com',
    storageBucket: 'prowork-a9a06.appspot.com',
    measurementId: 'G-C0KV6EHRG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHV-uA5TMR9jyC_BD7NORvv4dALgwnbGA',
    appId: '1:348036739477:android:0024d1700f47037d65c69c',
    messagingSenderId: '348036739477',
    projectId: 'prowork-a9a06',
    storageBucket: 'prowork-a9a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8q6XgP00Dx5apLTfZjoraCLII2rLco4g',
    appId: '1:348036739477:ios:6594741cf3ce348b65c69c',
    messagingSenderId: '348036739477',
    projectId: 'prowork-a9a06',
    storageBucket: 'prowork-a9a06.appspot.com',
    iosClientId: '348036739477-pu0mjv3pkpbkjkql61or7su7oe3turjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.proWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8q6XgP00Dx5apLTfZjoraCLII2rLco4g',
    appId: '1:348036739477:ios:4f446f66f2552a9165c69c',
    messagingSenderId: '348036739477',
    projectId: 'prowork-a9a06',
    storageBucket: 'prowork-a9a06.appspot.com',
    iosClientId: '348036739477-f2hvc6ajijm6rldcas20a4b9fk6pmf7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.proWork.RunnerTests',
  );
}
